### ISSUE TITLE
魅族手机 MediaInfo执行失败,你设置的文件不存在.您的设置是:null

### ISSUE THREAD

**Issue by yuhb0303** [Zhaoss/WeiXinRecordedDemo#104]
你好，魅族手机 MediaInfo执行失败,你设置的文件不存在.您的设置是:null，请问是什么问题。谢谢。

**Comment by Zhaoss** [comment]
录制出的视频文件是空 录制失败了

**Comment by 354420603** [comment]
> 你好，魅族手机 MediaInfo执行失败,你设置的文件不存在.您的设置是:null，请问是什么问题。谢谢。
我这台魅族邹忌也是一样的问题，你那个解决了吗
