### ISSUE TITLE
Android 9.0 报libutility.so has text relocations

### ISSUE THREAD

**Issue by menghuanfeixiang** [Zhaoss/WeiXinRecordedDemo#105]
Android 9.0 Pad 报java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.example.zhaoshuang.weixinrecordeddemo-vb3iJlLpGoU3qf0DrSFOqA==/lib/arm/libutility.so" has text relocations

请问这个问题怎么解决？

**Comment by Zhaoss** [comment]
就是初始化so库失败了呀 检查路径和包名 一个都不能错
