### ISSUE TITLE
魅蓝 note3 视频编辑失败

### ISSUE THREAD

**Issue by 354420603** [Zhaoss/WeiXinRecordedDemo#107]
//合成音频
String aacPath = mVideoEditor.executePcmEncodeAac(syntPcm(), RecordUtil.sampleRateInHz, RecordUtil.channelCount);

aacPath为空导致编辑失败，希望大佬能分析一下原因

**Comment by Zhaoss** [comment]
看看录制音频哪里 什么地方出问题了

**Comment by 354420603** [comment]
/**
     * 异步线程执行的代码.
     */
    public int executeVideoEditor(String[] array) {
        return execute(array);
    }
返回值为1，不是0


jni中怎么处理我就不知道了

**Comment by 354420603** [comment]
/**
     * 执行成功,返回0, 失败返回错误码.
     * <p>
     * 解析参数失败 返回1
     * sdk未授权 -1；
     * 解码器错误：69
     * 收到线程的中断信号：255
     * 如硬件编码器错误，则返回：26625---26630
     *
     * @param cmdArray ffmpeg命令的字符串数组, 可参考此文件中的各种方法举例来编写.
     * @return 执行成功, 返回0, 失败返回错误码.
     */
    private native int execute(Object cmdArray);

**Comment by 354420603** [comment]
> 看看录制音频哪里 什么地方出问题了

把targetVersion降到小于23可以使用，但高于23则编辑失败

**Comment by gushiyong** [comment]
我也遇到了同样的问题，魅族3在  boolean isH264ToMp4 = mVideoEditor.h264ToMp4(h264Path, mp4Path); 返回false 提示编辑失败
