### ISSUE TITLE
录制的视频时长怎么跟播放的时长不一致呢？该怎么修改呢？谢谢了

### ISSUE THREAD

**Issue by workertao** [Zhaoss/WeiXinRecordedDemo#108]
录制的视频时长怎么跟播放的时长不一致呢？该怎么修改呢？谢谢了

**Comment by Zhaoss** [comment]
时长过长 还是过小

**Comment by workertao** [comment]
录制10秒，在编辑完之后只有4~5秒。是压缩导致的吗？请问有什么办法不压缩吗？

**Comment by Zhaoss** [comment]
手机型号是什么  录制的过程中 有卡顿的现象吗

**Comment by workertao** [comment]
请问视频是不是进行了压缩操作呢？会不会是压缩导致的？如果有，怎么去掉压缩呢？

**Comment by Zhaoss** [comment]
不是压缩 是手机性能不够 导致编码的时候慢 写的帧数少

**Comment by workertao** [comment]
好吧，那这快有什么办法解决吗？

**Comment by weeksRen** [comment]
同问解决办法

**Comment by Zhaoss** [comment]
v4.4 修复在某些手机上录制出的视频时间会变短(自动补帧)
