### ISSUE TITLE
26版本录制一次后闪退解决方案

### ISSUE THREAD

**Issue by Xuqichang** [Zhaoss/WeiXinRecordedDemo#109]
SDK 版本为26时,小米手机, 只要录制视频一次后就闪退, 解决方案:  com.zhaoss.weixinrecorded.util.RecordUtil  中
在 release 中添加:
  audioOut.close();
   videoOut.close();
 关闭音频输出, 视频输出流即可

**Comment by Zhaoss** [comment]
谢谢提醒 已修正
