### ISSUE TITLE
是so文件的版本低了？

### ISSUE THREAD

**Issue by songixan** [Zhaoss/WeiXinRecordedDemo#11]
detected problems with app native libraries(please consult log for detail):libutility.so:text relocations

**Comment by Zhaoss** [comment]
so库最高版本是22

**Comment by Zhaoss** [comment]
so库最高支持版本是22

**Comment by hellosuperX** [comment]
现在我也是遇到这个版本问题。请问是怎么解决的

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
