### ISSUE TITLE
Unresolved Dependencies

### ISSUE THREAD

**Issue by abhijithrkrishna** [Zhaoss/WeiXinRecordedDemo#111]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :weixinrecorded.
ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :weixinrecorded.
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :weixinrecorded.

how to solve this ?

**Comment by Zhaoss** [comment]
Uploaded a new version

**Comment by abhijithrkrishna** [comment]
how to solve this?

**Comment by abhijithrkrishna** [comment]
same error occurred on the new build also.

**Comment by abhijithrkrishna** [comment]
when I try to rebuild or clean the project, it shows

Unable to find a matching configuration of project :weixinrecorded:
  - None of the consumable configurations have attributes.
