### ISSUE TITLE
Could not determine the dependencies

### ISSUE THREAD

**Issue by abhijithrkrishna** [Zhaoss/WeiXinRecordedDemo#113]
gradle project sync fails and shows error as

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :weixinrecorded.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :weixinrecorded.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :weixinrecorded.
Show Details
Affected Modules: app

then when I try to rebuild or clean the project it will show

Unable to find a matching configuration of project :weixinrecorded:
  - None of the consumable configurations have attributes.

**Comment by Zhaoss** [comment]
Tomorrow I will solve this problem

**Comment by abhijithrkrishna** [comment]
Thank you bro

**Comment by Zhaoss** [comment]
download new version
