### ISSUE TITLE
Issue on video and audio sync

### ISSUE THREAD

**Issue by abhijithrkrishna** [Zhaoss/WeiXinRecordedDemo#114]
After recording the preview and the saved video have issues

The video view is faster than the audio.because of that when I record a 60-sec video, the saved video will be 40 sec due to the fast video playback and the remaining audio will all be missed at last.
After the video saving process, the folder will have more than one video outputs for a recording with audio and without audio

Thank you

**Comment by abhijithrkrishna** [comment]
any solutions?

**Comment by Zhaoss** [comment]
v4.4 修复在某些手机上录制出的视频时间会变短(自动补帧)
