### ISSUE TITLE
作者您好！后续版本能自定义比例拍摄就完美了

### ISSUE THREAD

**Issue by androidxzc** [Zhaoss/WeiXinRecordedDemo#124]

**Comment by Zhaoss** [comment]
拍摄比例不是我们是自定义的  是camera这个对象返给我们可以使用的拍摄size  我们选取一个使用,
如果要实现比如正方形拍摄 可以使用view遮盖办法 形成用户视觉正方形 然后剪切视频宽高, 变成正方形视频
