### ISSUE TITLE
arm64-v8a 适配

### ISSUE THREAD

**Issue by tangandtang** [Zhaoss/WeiXinRecordedDemo#130]
你好，请问有arm64-v8a的适配的so库吗？libyuv-sample 64位的是否能提供一下

**Comment by Zhaoss** [comment]
https://github.com/LanSoSdk/LanSoEditor_common 建议来这里问问

**Comment by tangandtang** [comment]
这个sample.so不是您这边自己编译的吗？我在他们那边只找到其他几个so库对应的64位，没有找到有sample的，还望多多指教。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"赵爽"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 晚上7:04
收件人:&nbsp;"Zhaoss/WeiXinRecordedDemo"<WeiXinRecordedDemo@noreply.github.com&gt;;
抄送:&nbsp;"<br?/&gt;淡默如尘"<1663755595@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhaoss/WeiXinRecordedDemo] arm64-v8a 适配 (#130)




https://github.com/LanSoSdk/LanSoEditor_common 建议来这里问问
