### ISSUE TITLE
录制过程中，预览图象比例拉伸

### ISSUE THREAD

**Issue by DasinWong** [Zhaoss/WeiXinRecordedDemo#133]
在录制过程中，预览的图像“比例变长了”，分辨率时 2340 *1080 小米9，但是录制后保存的文件比例是正常的。@Zhaoss 感谢分享

**Comment by Zhaoss** [comment]
预览的TextureView宽高比要和摄像头输出一样比例 比如录制视频是16:9 预览的view也要是16:9

**Comment by DasinWong** [comment]
收到，感谢作者分享




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"赵爽"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月20日(星期五) 下午4:29
收件人:&nbsp;"Zhaoss/WeiXinRecordedDemo"<WeiXinRecordedDemo@noreply.github.com&gt;;
抄送:&nbsp;"王大心"<648683834@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhaoss/WeiXinRecordedDemo] 录制过程中，预览图象比例拉伸 (#133)





 
预览的TextureView宽高比要和摄像头输出一样比例 比如录制视频是16:9 预览的view也要是16:9
