### ISSUE TITLE
华为P30 pro使用前置摄像头录像只能偶尔成功，大部分时候报错：Unable to retrieve AudioRecord object

### ISSUE THREAD

**Issue by conjon** [Zhaoss/WeiXinRecordedDemo#145]
问题出在：com.zhaoss.weixinrecorded.util.RecordUtil的141行【startWhile()方法】
回调onError方法，报错：Unable to retrieve AudioRecord object

后置摄像头几乎都能成功，前置摄像头几乎都无法生成视频。

**Comment by Zhaoss** [comment]
先看下日志
