### ISSUE TITLE
请问编辑视频截取时候，进度回调不准问题怎么解决

### ISSUE THREAD

**Issue by Zhangxd77** [Zhaoss/WeiXinRecordedDemo#147]
就是在myVideoEditor.setOnProgessListener{
 @Override
            public void onProgress(VideoEditor v, int percent) {
}
}
时候，获取percent都是到百分之五六十，一下就成功了，并不是循序渐进的，

不知道是否有大佬解决了能给指点一下

**Comment by Zhaoss** [comment]
进度是按模块走的  不是实际编辑进度
