### ISSUE TITLE
这是一个案例，so库绑定包名，修改一下包名就不能用了。

### ISSUE THREAD

**Issue by learder** [Zhaoss/WeiXinRecordedDemo#155]
希望下次注明一下。。。测了一天了。。。

**Comment by learder** [comment]
整错

**Comment by learder** [comment]
正确使用方法：打包成aar，再直接引用，记得加混淆，如果想自己把代码复制到自己工程，会涉及到因为包名修改了，反射不到的问题。

**Comment by Zhaoss** [comment]
因为有挺多人问这个问题 我特意在文章的头部中加粗字体标明了包名问题 [https://www.jianshu.com/p/5a173841a828](url)
## 请注意! com.yixia的包名也要完整的copy过来, 要不然找不到so库, 会崩溃!

下次使用的时候建议大概看一眼文章, 毕竟我这不是一个库, 只是一个代码范例, 具体的应用是要开发者自己稍微理解下的

**Comment by learder** [comment]
好的好的，感谢。已弄明白。
