### ISSUE TITLE
华为P9黑屏

### ISSUE THREAD

**Issue by stayinxing** [Zhaoss/WeiXinRecordedDemo#16]

**Comment by Zhaoss** [comment]
自己看下log 是不是录制时初始化失败, 看下是不是分辨率没设对

**Comment by stayinxing** [comment]
ava.lang.RuntimeException: setParameters failed
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.hardware.Camera.setParameters(Camera.java:1722)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.yixia.camera.MediaRecorderBase.startPreview(MediaRecorderBase.java:525)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.yixia.camera.MediaRecorderBase.surfaceCreated(MediaRecorderBase.java:608)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:583)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.SurfaceView.access$000(SurfaceView.java:88)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1944)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1042)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5905)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:593)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:562)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.os.Looper.loop(Looper.java:136)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5314)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at dalvik.system.NativeStart.main(Native Method)
03-17 17:14:36.810 7160-7160/com.example.zhaoshuang.weixinrecordeddemo E/Yixia: startPreview fail :setParameters failed

看来是预览失败了。


关于摄像头的适配，还是不能写死了。应该动态的去适配吧。还有，有的手机前置摄像头拍出来是倒的。能不能解决下。

**Comment by stayinxing** [comment]
/**
 * 获取所有支持的预览尺寸
 *
 * @param list
 * @param minWidth
 * @return
 */
public Size getPropPreviewSize(List<Size> list, int minWidth) {
    Collections.sort(list, ascendSizeComparator);

    int i = 0;
    for (Size s : list) {
        if ((s.width >= minWidth)) {
            break;
        }
        i++;
    }
    if (i == list.size()) {
        i = 0;//如果没找到，就选最小的size
    }
    return list.get(i);
}
能不能把动态获取设备支持的尺寸加上啊。兼容性问题伤不起。

**Comment by stayinxing** [comment]
上面个那个黑屏日志，是因为尺寸不对吗？

**Comment by Zhaoss** [comment]
是的 setParameters我用到的有两点 一个是手动对焦 还有就是设置宽高  你这个应该就是录制宽高 动态配置宽高你自己做一下就行了啊  我这只是一个demo而已
