### ISSUE TITLE
编译版本23时 没用了

### ISSUE THREAD

**Issue by githubwxq** [Zhaoss/WeiXinRecordedDemo#20]

**Comment by Zhaoss** [comment]
因为本地的libutiliyt编译的版本是23以下的, 所以如果编译版本为23或以上时, 就会UnsatisfiedLinkError错误

**Comment by justziyang** [comment]
请问解决了么？我的也是so的编译版本过低，项目编译版本现在是25，而且降不下来，怎么办？

**Comment by hellosuperX** [comment]
同样的疑问。请问作者解决了吗

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
