### ISSUE TITLE
您好，我公司项目编译版本是25的，so的版本大于22就不能用了，想问下有什么好的方法么？

### ISSUE THREAD

**Issue by justziyang** [Zhaoss/WeiXinRecordedDemo#21]
您好，我公司项目编译版本是25的，so的版本大于22就不能用了，想问下有什么好的方法么？

**Comment by Zhaoss** [comment]
没有办法 因为so库的编译版本就是小于23的

**Comment by justziyang** [comment]
或者您用的so文件是从哪里找的呢？能给我提供一下链接什么的么？我尝试一下能不能找到高一点的编译版本的so文件。非常感谢。

**Comment by Zhaoss** [comment]
vcamera 百度一下

**Comment by fishsoft** [comment]
@justziyang 你好，兼容高版本的问题你解决了吗？可否共享一下或者提供一下可行的想法？谢谢！

**Comment by justziyang** [comment]
@fishsoft 解决不了，so库问题，只能问一下他们官方的人员了，而且这个是个人免费，企业收费的。。

**Comment by fishsoft** [comment]
@justziyang thank you

**Comment by amelons** [comment]
兄弟们谁解决了，给个23及23版本以上的.so文件

**Comment by amelons** [comment]
@fishsoft 哥们这个so编译版本问题，你那边解决了吗

**Comment by wangchunfei** [comment]
同样遇到这个问题了，有解决方法的老哥说一下

**Comment by Zhaoss** [comment]
我过段时间 会上传一个3.0版本 在那个版本里 我会自己重新编译ffmpeg库  不会用第三方的库了

**Comment by CristianoLi** [comment]
你好，so文件23以上版本的问题解决了吗？

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
