### ISSUE TITLE
初始化时获取sd卡文件路径有问题

### ISSUE THREAD

**Issue by qazhuhuihao** [Zhaoss/WeiXinRecordedDemo#22]
建议把String VIDEO_PATH = "/sdcard/WeiXinRecordedDemo/";改成
String VIDEO_PATH = Environment.getExternalStorageDirectory().getPath()+"/WeiXinRecordedDemo/";

**Comment by Zhaoss** [comment]
恩 一个demo我能简单就直接写死了 如要要移动到项目里用 好多东西都要动态适配 比如相机参数 录制宽高等等
