### ISSUE TITLE
您好，感谢您的分享，这里有个关于gif叠加到视频的问题，希望能够给一个思路，感谢！

### ISSUE THREAD

**Issue by BryceLee** [Zhaoss/WeiXinRecordedDemo#26]
您项目中，是把RelativeLayout中的所有涂鸦层绘制成一个bitmap.-->jpeg,然后叠加到视频上，这里遇到一个需求，请问如何添加到图片可能是动态的gif，这时候可以连同其他涂鸦生成一个gif，再叠加上去嘛？如果可以应该Canva要如何绘制呢？感谢🙏！

**Comment by zacksky** [comment]
你好，同样遇到gif动态贴图的问题，有什么解决方案吗？
