### ISSUE TITLE
重要BUG

### ISSUE THREAD

**Issue by SunShaoNing** [Zhaoss/WeiXinRecordedDemo#27]
只能录制一次，第一次进入录制，取消再录制，完全没问题，当退出这个activity，再跳入这个activity的时候录制时只有第一秒的视频保存下来了，求解决！！！！！只有把整个程序退出重来才行！

**Comment by Zhaoss** [comment]
我在back键 和页面关闭都有做文件删除和对象释放 你自己看看那里的逻辑有没问题

**Comment by SunShaoNing** [comment]
释放掉再进去就不行了吗？

**Comment by Zhaoss** [comment]
我刚才试了几次 拍摄完取消, 拍摄完成到下一个界面, 都没有问题 可以继续拍 拍出的视频也是正常的

**Comment by SunShaoNing** [comment]
你拍完一次退一下，再进，别拍完返回直接拍，你拍完了退出程序再进去试试，这个BUG是必出的，我是把你的集成到项目中的是从别的activity跳进去 的，拍完返回本activity，再进去 就不行了，必出这个Bug!

**Comment by Zhaoss** [comment]
我新的代码提交了 你试一下

**Comment by SunShaoNing** [comment]
改了哪里了

**Comment by SunShaoNing** [comment]
v2.2中问题解决！！！棒！！！
