### ISSUE TITLE
请问怎么拿到录制的视频的首帧图额？

### ISSUE THREAD

**Issue by hyr0318** [Zhaoss/WeiXinRecordedDemo#28]
如题，getOutputVideoThumbPath。能拿到一个图片的地址，但是好像不能设置到imageview 上 是什么问题额

**Comment by Zhaoss** [comment]
ffmpeg有语法 你自己看下 可以得到视频第一帧

**Comment by hyr0318** [comment]
@Zhaoss  可以帮忙贴出来么。不知道怎么弄，一直获取不到额。

**Comment by hyr0318** [comment]
还有一个就是录制时候的画面很模糊，这个调什么配置额？ 谢谢哈

**Comment by Zhaoss** [comment]
ThumbnailUtils.createVideoThumbnail(videoPath,MediaStore.Video.Thumbnails.FULL_SCREEN_KIND)
这是android自带的取视频封面的方法 比ffmpeg效率高 录制视频宽高我现在是800x600, 我现在调整成1280x720了 你可以重新下载一下代码 我这些配置在简书里面都有讲解的  遇到不懂的你先好好看源码讲解啊

**Comment by hyr0318** [comment]
@Zhaoss  我是用的官方的jar包集成的额，不是用你的这个额。好像没有提供设置宽高的方法吧？ 还有
Bitmap videoThumbnail = ThumbnailUtils.createVideoThumbnail(
            mMediaObject.getOutputVideoPath(), MediaStore.Video.Thumbnails.MINI_KIND);

这个返回的是空额。

**Comment by hyr0318** [comment]
@Zhaoss  首帧图的问题解决啦，用的jar包的形式， 用什么方法来设置分辨率的额？ 求助

**Comment by liangjiaxuan** [comment]
@hyr0318 怎么解决的  求助

**Comment by hyr0318** [comment]
@liangjiaxuan ThumbnailUtils.createVideoThumbnail(
mMediaObject.getOutputVideoPath(), MediaStore.Video.Thumbnails.MINI_KIND); 就是用的这个。如果拿不到 你看下路径是不是对的。

**Comment by hyr0318** [comment]
@liangjiaxuan  但是一只不知道怎么改输出的分辨率，录出来的好模糊
