### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by powerwolfman** [Zhaoss/WeiXinRecordedDemo#31]
我导入jar包的时候，VCamera.initialize(this);这句话一调用就报jni错误，但是我导入module使用的时候， java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.haosen.xueshengshitangwang-1/lib/arm/libutility.so: has text relocations
是这样一个错误，
static {
		System.loadLibrary("utility");
	}
错误指向这儿，这个看怎么解决

**Comment by Zhaoss** [comment]
找不到类库 自己看看包名是不是完整的copy过来了

**Comment by ejwdhr** [comment]
你搞好没有
