### ISSUE TITLE
前置摄像头录制的视频，播放时倒立显示

### ISSUE THREAD

**Issue by Owen-Hw** [Zhaoss/WeiXinRecordedDemo#33]
后置摄像头录制的视频播放的时候是正常的；
前置摄像头录制的视频，播放的时候变成里倒立。
已添加如下代码，不起作用：
  if (mCameraId == Camera.CameraInfo.CAMERA_FACING_BACK) {
            UtilityAdapter.RenderInputSettings(MediaRecorderBase.VIDEO_WIDTH, MediaRecorderBase.VIDEO_HEIGHT, 0, UtilityAdapter.FLIPTYPE_NORMAL);
        } else {
            UtilityAdapter.RenderInputSettings(MediaRecorderBase.VIDEO_WIDTH, MediaRecorderBase.VIDEO_HEIGHT, 180, UtilityAdapter.FLIPTYPE_HORIZONTAL);
        }

**Comment by Zhaoss** [comment]
v2.3版本已经提交 问题解决
