### ISSUE TITLE
录制完成

### ISSUE THREAD

**Issue by ly469097645** [Zhaoss/WeiXinRecordedDemo#36]
前置摄像头录制过程中是正常的，录制结束后播放还是倒过来的

**Comment by Zhaoss** [comment]
刚用华为荣耀7 测试没有问题 说下出问题的手机型号

**Comment by ly469097645** [comment]
小米6

**Comment by ly469097645** [comment]
我测试了两个手机，一个小米6，一个华为荣耀note8，都是观看前置摄像头录制的视频倒过来了，而且还有一个就是假如没有先使用后置摄像头录制过，而是一进demo就切换前置摄像头录制，就会卡在合成中的对话框，如果先用后置摄像头录制之后再切换前置摄像头录制就可以合成成功

**Comment by Zhaoss** [comment]
mainactivity里面 rotateVideo2(String path, float angle, String output)方法 angle参数是旋转角度 你试下改变这个参数

**Comment by Zhaoss** [comment]
就会卡在合成中的对话框
这个问题不是卡在合成对话框中 是速度很慢 因为在使用软解旋转视频源码文件 这个so库很老 所以对硬解支持不是很好 你等一会 他就会编译完成的
