### ISSUE TITLE
使用前置摄像头拍摄一直是视频合成中

### ISSUE THREAD

**Issue by bertsir** [Zhaoss/WeiXinRecordedDemo#39]
如题

**Comment by Zhaoss** [comment]
你自己debug一下 看看卡在哪里了

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
