### ISSUE TITLE
按下电源键以后屏幕变黑 但是还会有声音

### ISSUE THREAD

**Issue by linghushaohong** [Zhaoss/WeiXinRecordedDemo#43]
按下电源键以后屏幕变黑 但是还会有声音，但是点击home键以后就不会有，调试了走的方法都一样，请问一下这个问题怎么解决啊

**Comment by Zhaoss** [comment]
在播放视频界面会变黑?  你在onresume里面判断一下

**Comment by Zhaoss** [comment]
在播放视频界面会变黑? 你在onPause里面判断一下

**Comment by linghushaohong** [comment]
是当我在预览视频的时候 我按下电源键锁屏了但是声音还在播放
