### ISSUE TITLE
关于libutility.so文件的问题

### ISSUE THREAD

**Issue by BeatGeneration** [Zhaoss/WeiXinRecordedDemo#47]
请教一下，这个libutility.so文件我在VCamera官网上没有找到啊，现在我的项目arm64-v8a里面有别的so文件不能删除，有没有什么可以解决的办法，先谢谢你啦

**Comment by KnIfER** [comment]
散了吧 都是假开源 套路

**Comment by Zhaoss** [comment]
一想到我的开源要被你这种人用，真是恶心

**Comment by KnIfER** [comment]
re:想到我的开源要被你这种人用，真是恶心
放心，这种假开源我是懒得下载，就算下载了也是懒得放到IDE里面去。
你眼睛里都是蛆虫吧看你老子都恶心。
特么的这种假开源还装碧莲哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈
