### ISSUE TITLE
多段视频录制合成后，该视频时长与视频播放时长不一致，求助

### ISSUE THREAD

**Issue by Neils320** [Zhaoss/WeiXinRecordedDemo#50]
多段视频录制合成后，查看该视频时长与视频播放时长不一致；
时间跳动很快，请问能有办法解决吗，求助
demo会出现相同情况

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
