### ISSUE TITLE
关于视频剪辑的一些问题

### ISSUE THREAD

**Issue by littledifficult** [Zhaoss/WeiXinRecordedDemo#53]
作者你好，视频剪辑那个activity 你的ffmpeg语句写错了，还有那个下方的剪辑进度条怎么控制最小长度为多少秒，剪辑进度条变化时能不能弄出播放预览效果       非常感谢分享

**Comment by protectedMan** [comment]
同问

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
