### ISSUE TITLE
点击拍照有bug

### ISSUE THREAD

**Issue by IvesZY** [Zhaoss/WeiXinRecordedDemo#54]
点击拍照的时候，合成照片的方法，使用MediaMetadaRetriever.getFrameAtTime(1);得到的bitmap有时候是空指针，这个怎么解决

**Comment by Zhaoss** [comment]
RecordedActivity.class 里面的  myHandler.sendEmptyMessageDelayed(HANDLER_CAMERA_PHOTO, 30);   30变成100试下  应该是机器性能不够 30毫秒没有抓取到一帧图片

**Comment by IvesZY** [comment]
谢谢大佬，我换了部测试机，按照你说的方法是可以的
