### ISSUE TITLE
detected problems with app native libraries

### ISSUE THREAD

**Issue by h35765469** [Zhaoss/WeiXinRecordedDemo#56]
這個問題好奇怪，ㄧ開啟相機就出現這個警告dialog，有誰知道發生什麼事嗎?

**Comment by Zhaoss** [comment]
sdk版本提示  打包apk 就没这问题了

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
