### ISSUE TITLE
视频分片合成问题

### ISSUE THREAD

**Issue by Yuphee** [Zhaoss/WeiXinRecordedDemo#57]
List<String> pathList = new ArrayList<>();
                for (int x = 0; x < mMediaObject.getMediaParts().size(); x++) {
                    MediaObject.MediaPart mediaPart = mMediaObject.getMediaParts().get(x);

                    String mp4Path = SDKUtil.VIDEO_PATH+"/"+x+".mp4";
                    List<String> list = new ArrayList<>();
                    list.add(mediaPart.mediaPath);
                    ts2Mp4(list, mp4Path);
                    pathList.add(mp4Path);
                }

                List<String> tsList = new ArrayList<>();
                for (int x = 0; x < pathList.size(); x++) {
                    String path = pathList.get(x);
                    String ts = SDKUtil.VIDEO_PATH+"/"+x+".ts";
                    mp4ToTs(path, ts);
                    tsList.add(ts);
                }

                String output = SDKUtil.VIDEO_PATH+"/finish.mp4";
                boolean flag = ts2Mp4(tsList, output);
                if(!flag) output = "";
                deleteDirRoom(new File(SDKUtil.VIDEO_PATH), output);
                return output;
            }
这段代码为什么要先把n个ts分片弄成n个mp4再弄成n个ts分片再合成一个mp4意义何在？

**Comment by Zhaoss** [comment]
以前有可能 1段视频是后置拍摄 2段视频是前置拍摄 我要旋转前置视频180度 来统一合成后的视频旋转角度;  后来我直接在拍摄时编码旋转角度了 然后这里的代码忘优化 你可以改一下
