### ISSUE TITLE
红米note4使用该demo,将录制时间从默认8s改成120s.录制到60s左右,app崩溃.

### ISSUE THREAD

**Issue by manuchen** [Zhaoss/WeiXinRecordedDemo#58]
红米note4使用该demo,将录制时间从默认8s改成120s.录制到60s左右,app崩溃.
补充bug信息:
1.正常录制(有光线正常取景)60s左右崩溃,非正常录制(黑暗中)崩溃次数低3次有一次崩
2.输出log日志,按关键字搜索exception,暂没发现跟demo相关的报错信息.
3.将腾讯bugly集成进来,也没抓取到类似null指针这种的明显的报错信息.

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
