### ISSUE TITLE
可以不使用VCamera的so吗

### ISSUE THREAD

**Issue by imishx** [Zhaoss/WeiXinRecordedDemo#59]

**Comment by Zhaoss** [comment]
我尝试编写过 但是关于视频拍摄每帧转码这里有问题 还是需要专业的人来编写so库

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
