### ISSUE TITLE
华为Mate9 8.0系统闪退

### ISSUE THREAD

**Issue by yangqicong11** [Zhaoss/WeiXinRecordedDemo#60]
targetSdkVersion 23 打开就提示dlopen failed libutility.so 项目里有动态权限 ，没办法把targetSdkVersion调到22，有什么其他解决办法吗？

**Comment by hellosuperX** [comment]
我现在也是卡在这里。没法有动态权限。这就很尴尬

**Comment by KevinLium** [comment]
打开预览之前 先申请下权限不行吗？

**Comment by yangfeng1994** [comment]
请问几位大佬，是怎么解决的？

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
