### ISSUE TITLE
请教大佬，如何使点按拍照的照片更加清晰

### ISSUE THREAD

**Issue by IvesZY** [Zhaoss/WeiXinRecordedDemo#63]
看代码，照片也是从视频里面获取最近的第一帧吧，然后我设置视频的宽为1920，高1080，码率是4M，对清晰度没有效果啊

**Comment by Zhaoss** [comment]
Parameters.getSupportedPreviewSizes() 得到摄像头支持规格 因为是照片 所以可以设置高一点,
myHandler.sendEmptyMessageDelayed(HANDLER_CAMERA_PHOTO, 30) 这行代码 30可以改成100或者更高 为的是等对焦更准确一点再抓取图片
