### ISSUE TITLE
android 进入视频页面有这个弹框

### ISSUE THREAD

**Issue by yuexiaodong1** [Zhaoss/WeiXinRecordedDemo#64]
detacted problems with app native librarues piease consult log for detali libutility.so text relocations

**Comment by Zhaoss** [comment]
打完包就没有了 直接run会出现

**Comment by yuexiaodong1** [comment]
知道了，混淆有哪些东西啊

**Comment by Zhaoss** [comment]
整个modle别混就行

**Comment by yuexiaodong1** [comment]
主工程混淆开启了，子模块不开启也是被混淆的

**Comment by Zhaoss** [comment]
我说的是你把weixinrecorded这个modle全都加入防混淆名单

**Comment by CristianoLi** [comment]
你好，so文件不支持23及以上的问题你是怎么解决的？

**Comment by yuexiaodong1** [comment]
我只是做demo用，没应用到项目里面
