### ISSUE TITLE
镜像

### ISSUE THREAD

**Issue by DreamerHzy** [Zhaoss/WeiXinRecordedDemo#71]
作者你好，我发现项目当打开前置摄像头时，拍照或摄像后的图片或者视频都是跟预览相反的（也就是镜像了），请问在哪里可以设置？

**Comment by DreamerHzy** [comment]
在项目中照片合成的地方加上镜子效果就可实现。
相关代码：
Matrix matrix = new Matrix();
matrix.setScale(-1, 1);
matrix.postTranslate(photo.getWidth(), 0);
photo = Bitmap.createBitmap(photo, 0, 0, photo.getWidth(), photo.getHeight(), matrix, true);

**Comment by bubble96** [comment]
大神求教，如果是视频的话，镜像因该怎么实现？

**Comment by Zhaoss** [comment]
v4.3 使用libyuv库进行视频帧的旋转和镜像, 优化录制性能
