### ISSUE TITLE
是包名的问题。。感谢

### ISSUE THREAD

**Issue by zmenglei** [Zhaoss/WeiXinRecordedDemo#74]
_Originally posted by @ly469097645 in https://github.com/Zhaoss/WeiXinRecordedDemo/issues/12#issuecomment-286292070_哪的包名问题啊？急~

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
