### ISSUE TITLE
视频变形拉伸怎么办

### ISSUE THREAD

**Issue by zhangnanvip** [Zhaoss/WeiXinRecordedDemo#75]
视频变形拉伸怎么办

**Comment by Botision** [comment]
我也遇到这个问题，请问下您是如何解决的呢

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度

**Comment by Botision** [comment]
非常感谢您

**Comment by zhangshaobo87** [comment]
使用前置摄像头全屏录制视频的时候，预览画面被拉伸变形了
