### ISSUE TITLE
UI上的bug： 长按按钮拍摄，几次断点后，短按后 拍摄按钮显示异常。不会还原大小

### ISSUE THREAD

**Issue by yunshuwanli** [Zhaoss/WeiXinRecordedDemo#76]
长按按钮拍摄，几次断点后，短按后 拍摄按钮显示异常。不会还原大小。

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
