### ISSUE TITLE
tag版本，商店要求26以上了。。 

### ISSUE THREAD

**Issue by hellosuperX** [Zhaoss/WeiXinRecordedDemo#80]
so版本年后，应用商店要求26以上，请问适配so重定向问题如何解决

**Comment by wangyuan0217** [comment]
同问，因为这个用不了这个库了。

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
