### ISSUE TITLE
裁剪按钮无反应

### ISSUE THREAD

**Issue by ruanguihua** [Zhaoss/WeiXinRecordedDemo#82]

**Comment by a120476536** [comment]
我也是剪切视频按钮点了没啥反应

**Comment by anonym2** [comment]
您对该文件没有任何问题  libutility.so ?

**Comment by Zhaoss** [comment]
已更新4.0版本 
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
