### ISSUE TITLE
Pad横屏录制横屏播放

### ISSUE THREAD

**Issue by menghuanfeixiang** [Zhaoss/WeiXinRecordedDemo#87]
pad横屏录制可以实现，但录制后的视屏只能竖屏播放。如何做到录制后的视频是横屏的？
String cmd = String.format("filename = \"%s\"; ", result.mediaPath);
cmd += String.format("addcmd = %s; ", " -vf \"transpose="+cameraState+"\" ");

transpose值，0、1、2、3四个值我都试过了，还是没有达到预期效果

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度

**Comment by Zhaoss** [comment]
已更新4.0版本
更新ffmpeg库文件,适配target26以上版本,使用Camera源+MediaCodec编码录制视频和音频,优化编码速度
