### ISSUE TITLE
视频时长不对，音视频不同步

### ISSUE THREAD

**Issue by zhujunhua2012** [Zhaoss/WeiXinRecordedDemo#91]
录制完成后，不进行编辑，直接点击完成。
合成后的视频，使用其他播放器，显示时长为 51秒（实际录制时长限制最大30秒，录制最长的30秒）。视频中的音频和视频不同步。
生成的aac文件，时长是正确的30秒。但是视频时长较大。

备注：
已使用最新的代码，及最新的so库（包括64位的）

https://github.com/LanSoSdk/LanSoEditor_common 已更新arm64的so

**Comment by Zhaoss** [comment]
更新了新版本 换了一种音频编码方式
