### ISSUE TITLE
/lib/arm64-v8a，/system/lib64，/system/vendor/lib64]]]找不到“liblansongffmpeg.so

### ISSUE THREAD

**Issue by xulongchao1994** [Zhaoss/WeiXinRecordedDemo#92]
我不能只留一个so包文件夹，因为别的文件夹里还有别的包，这个liblansongffmpeg.so去哪找？

**Comment by Zhaoss** [comment]
https://github.com/LanSoSdk/LanSoEditor_common 你可以去这问问有别的库文件吗
