### ISSUE TITLE
录制视频的时长和文件夹里面的视频的时长不一致

### ISSUE THREAD

**Issue by IvesZY** [Zhaoss/WeiXinRecordedDemo#94]
录制十秒的视频，我在文件夹上视频大小有近十M，而且播放视频的时长哟有十六秒，请问大佬，该怎么解决

**Comment by IvesZY** [comment]
用的是4.0的版本，十秒的视频是一次性录完

**Comment by Zhaoss** [comment]
之前版本音频编码有问题 我更新到4.2了  你看看解决没

**Comment by IvesZY** [comment]
我是今天download您GitHub上的源码运行的

**Comment by IvesZY** [comment]
应该是4.2的版本了，我看readme,以为是4.0的

**Comment by IvesZY** [comment]
我发现录制十秒的视频，h264转成的第一个视频.ts就是十五秒的视频，我估计应该是h264转Ts有点问题

**Comment by IvesZY** [comment]
我用播放器播放h264d的视频就是十五秒的，请问大佬，怎么解决

**Comment by Zhaoss** [comment]
h264编码有问题 手机性能越高 视频时间越长 在解决 别问了

**Comment by IvesZY** [comment]
嘿嘿，麻烦大佬了

**Comment by Zhaoss** [comment]
提交了新版本 试试看

**Comment by IvesZY** [comment]
感谢大佬，正常录制的情况下时长是一致的，但是先录制几秒，松手，然后切换摄像头，在进行录制，还是会丢失，录制十秒的视频，只有六秒左右

**Comment by swallowsonny** [comment]
我下载demo后。录制10s的视频，文件夹中播放只有5s

**Comment by IvesZY** [comment]
> 我下载demo后。录制10s的视频，文件夹中播放只有5s

你下载大佬的4.2.2版本，我这边是可以的

**Comment by Zhaoss** [comment]
> 感谢大佬，正常录制的情况下时长是一致的，但是先录制几秒，松手，然后切换摄像头，在进行录制，还是会丢失，录制十秒的视频，只有六秒左右

我用小米和oppo测试 都没问题 视频录制时长不对 是因为性能 性能高视频长 性能低视频短

**Comment by IvesZY** [comment]
> > 感谢大佬，正常录制的情况下时长是一致的，但是先录制几秒，松手，然后切换摄像头，在进行录制，还是会丢失，录制十秒的视频，只有六秒左右
> 
> 我用小米和oppo测试 都没问题 视频录制时长不对 是因为性能 性能高视频长 性能低视频短

我用oppo R11t 8.1的安卓版本和红米5Plus 7.1.2的安卓版本，还有华为荣耀V8 安卓8.0的版本测试的；大佬，你试试切换摄像头

**Comment by Zhaoss** [comment]
> > > 感谢大佬，正常录制的情况下时长是一致的，但是先录制几秒，松手，然后切换摄像头，在进行录制，还是会丢失，录制十秒的视频，只有六秒左右
> > 
> > 
> > 我用小米和oppo测试 都没问题 视频录制时长不对 是因为性能 性能高视频长 性能低视频短
> 
> 我用oppo R11t 8.1的安卓版本和红米5Plus 7.1.2的安卓版本，还有华为荣耀V8 安卓8.0的版本测试的；大佬，你试试切换摄像头

我这拿oppo r9s测试的 录10秒 出10秒视频 真没问题

**Comment by Zhaoss** [comment]
你录制5秒前置 5秒后置  然后去文件夹看每个ts文件的长度

**Comment by IvesZY** [comment]
> 你录制5秒前置 5秒后置 然后去文件夹看每个ts文件的长度
恩恩，不是必现的；如果长时间录制出现这种情况，应该如何处理？’

**Comment by Zhaoss** [comment]
性能高视频长 性能低视频短  我目前的处理是性能高删帧, 性能低没处理  如果要弄的话 就是性能低补帧

**Comment by IvesZY** [comment]
> 性能高视频长 性能低视频短 我目前的处理是性能高删帧, 性能低没处理 如果要弄的话 就是性能低补帧

好的，感谢大佬

**Comment by reichin** [comment]
下载的最新Demo。录制10s的视频，文件夹中播放只有5s。用的是华为手机。有什么好的解决方法吗？
