### ISSUE TITLE
剪切视频时获取视频关键帧很慢= =

### ISSUE THREAD

**Issue by Blablablar** [Zhaoss/WeiXinRecordedDemo#96]

**Comment by Blablablar** [comment]
我改用了MediaMetadataRetriever.getFrameAtTime() 速度很快，去掉了rxjava的方式在主线程同步获取，大视频也基本是秒获取到。然后还有mMediaPlayer只有裁剪成功的情况stop了，返回的时候没有stop

**Comment by Zhangxd77** [comment]
求问 视频获取关键帧很慢  MediaMetadataRetriever.getFrameAtTime() 怎么用
