### ISSUE TITLE
视频和图片显示旋转了90度

### ISSUE THREAD

**Issue by swallowsonny** [Zhaoss/WeiXinRecordedDemo#97]
手机图片与视频拍摄显示正常，但是上传服务器后，显示的结果旋转了90度

**Comment by swallowsonny** [comment]
还有录制的视频都只有 2s钟

**Comment by Zhaoss** [comment]
视频录制出来本来就是旋转90度的 我在视频元数据里加了旋转90度播放参数 所以他播放出来是正常的 你可以用ffmpeg来旋转视频源数据 但是会很慢
